version: '3'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
